### ISSUE TITLE
Source code Zip's are empty

### ISSUE THREAD

**Issue by UnderstandingTravis** [newbeedrone/Project-Mockingbird-Hummingbird-V1#1]
the source code Zip's  at 
https://github.com/newbeedrone/Project-Mockingbird-Hummingbird-V1/releases/tag/v1.1
are empty :-(
well the have the ReadMe.md but no code to edit.
i wanted to try to adjust my Hummingbird's tune to slow it down to make it easier for my friends. its great indoors and recovers from wall bumps well but its to fast and sensitive for regular people. ( i did this to my tinyhawk and have a rate profile i switch to for friends, It helps the hobby grow when people don't crash right away )

**Comment by icemanx** [comment]
Hi @UnderstandingTravis . The project is not open source. It just contains the production hex files for users to help reflashing the software.
